const fill = "transparent",
  blockStroke = "red",
  shelveStroke = "blue",
  columnStroke = "green",
  strokeWidth = 2,
  blockPrefix = "Block-",
  shelvePrefix = "Shelve-",
  columnPrefix = "Column-",
  columnStackPrefix = "ColumnStack-",
  lockScalingY = true,
  lockMovementX = true,
  lockMovementY = true,
  strokeUniform = true,
  blockPadding = 10,
  blockStrokeWidth = 5;

const blockConfig = {
    fill,
    strokeWidth: blockStrokeWidth,
    stroke: blockStroke,
    padding: blockPadding,
    strokeUniform,
    lockScalingY,
    lockMovementX,
    lockMovementY,
  },
  sheleveConfig = {
    fill,
    strokeWidth,
    stroke: shelveStroke,
    strokeUniform,
  },
  columnConfig = {
    fill,
    strokeWidth,
    stroke: columnStroke,
    strokeUniform,
  };

export {
  fill,
  blockStroke,
  shelveStroke,
  columnStroke,
  strokeWidth,
  blockPrefix,
  shelvePrefix,
  columnPrefix,
  columnStackPrefix,
  lockScalingY,
  lockMovementX,
  lockMovementY,
  strokeUniform,
  blockConfig,
  sheleveConfig,
  columnConfig,
  blockPadding,
  blockStrokeWidth,
};
